#!/usr/bin/env bash
# Auto-start NetworkManager on boot
systemctl start NetworkManager 2>/dev/null

echo ""
echo "========================================="
echo "  SSD Toolbox Live Environment"
echo "========================================="
echo ""
echo "Available tools:"
echo "  nvme-cli        - NVMe SSD management"
echo "  smartctl        - SMART monitoring"
echo "  hdparm          - ATA/SATA parameters"
echo "  hdsentinel      - Hard Disk Sentinel"
echo "  sdparm          - SCSI disk parameters"
echo "  blkdiscard      - Discard/TRIM sectors"
echo "  parted          - Partition management"
echo "  ssd-flash-id    - SSD flash ID detection"
echo "  intel-mas       - Intel Memory & Storage Tool"
echo "  kingston_fw_updater - Kingston FW updater"
echo "  samsung_magician - Samsung Magician CLI"
echo "  ocz-ssd-utility - OCZ SSD Utility"
echo "  ocztoolbox      - OCZ Toolbox"
echo "  oczclout        - OCZ/Toshiba CLout"
echo "  wd-fw-update    - WD firmware updater"
echo "  lsblk / lspci / lsusb / dmidecode / lshw"
echo ""
echo "Quick start:"
echo "  lsblk                    - List block devices"
echo "  nvme list                - List NVMe drives"
echo "  smartctl -a /dev/sdX     - Full SMART report"
echo "  nvme smart-log /dev/nvmeX - NVMe SMART log"
echo "========================================="
echo ""
